language: java
jdk:
- openjdk11
cache:
  directories:
  - "$HOME/.m2/repository"
branches:
  only:
  - master
  - "/^iterator-library-[0-9]+\\.[0-9]+\\.[0-9]+/"
after_success:
- test "${TRAVIS_PULL_REQUEST}" == "false" && test "${TRAVIS_TAG}" != "" && mvn deploy
  --settings settings.xml
env:
  global:
  - secure: DM/7sGHMoeOq1DxVQ+hbNpNF8xpqX832KxSfrTqiqdIu+AC8VFx1RUwuSfqmcIObUTicUMlPkoXdQ8SSsenLNBSMaD4JPIAePjeHi8pY+O/az0pNUi/mjElXPcG/gwg9Vnck/mhJP6BkCX51hnd6cgXN0ERFF/Opr2NBDi7dUmu6+pTB5+/EB6YEVFmBZrj1eLL0e3WjSlSFM2WkD3XzNx2NfSiwmjtl3J/JSec6EbBiQgrKIsdIWXv1FlrMcvdfP4k14fJFOkaut92I+PKCexPLYtgdypDShgqYsX39sbjbNnTaAyK/LaXSTt5cDMuDPwaFoCxVNTle+VcCkrggYooIuET7mueyhi6g9prs+algrIVpw5pGmUHNg4Eb9DjiqCe4YFoAjCJBWHWEVc0HZM7LmYPZ74hv8+GjoocM2Ur2WILWpNV8hVjAY/tREcX1yUNra1mj94oUuVxgRbCS58SXSPFU8Q0u0rKBop9PxbJysuVCQQWZb+V8HTT8MyBnN03CwC1o+icvSAtc6Y4E+HnVv3mnViWzt+D2WjQrm+aJpPmckM7w2o2qtamk4z57KweEev/2rQ9XHfrbiCxFIJ+O9NsEGAjZlePS2bw1KUs8eKwIjObw1g12aGTd76x76rrWD3kLsltc3RWP0iRlp2LI9G09YE1sm+8/i//qVDk=
  - secure: cVqRaMy0BV4t2/DUGKWn901pbs+Cs4sExlS0Iv8IhcvbfwJfSVEL9E5s+bJHO49daWcYCUKYVSeO8NWGlbiemYLEFVLVZxe4mZ+p48Eo+4TI9FsIHwpNtm6Dw9UC9lWNVvXF5gqKKBel2ZU1+v2+662hlbyIg7wuRIFxQR23G21Kena+2d3PUckyM59YCgMdwsIfg10Jnc1JVhhJsLKBccVJGZTaFkdf1nsPkpYxCHfamsk7Zht8isBDqf0fIgU33f2n3VX5nTUEwtJiJA3Yqqx1hutOL7J3Qh7HFfCGbhIMAj+H/q3r9FeOnK6caIamA6AQ4NQod1go/rXeDc4QiRZin1e9HpaM82pmsI1sirAX9ZP3/pAAcpHh9OlIb+ShUYtloLUrIAO9yoljZTRv4HUa/F0jPPxVbg7XLcX7BMFbOIPCDzN3+hwTXI5c5lwDQBFJLwWxTJ0H7tn8RusN6Kwh5mTd3FqD7ssuql4ZGWi6VuitUDsAugtxzJU89scef6qaO9dERGaV7oZwi+Q2R5MGhov0KIeSy/RoYKiCjMvyXTchktdudZz3mE7f8Dq5bQYbxfTV7yXQcEyN2FOt+QTKEJnSSXocS2+4O7uTUtF7ZAS82f+Qswtw7dYYwDGRqDWujScOgoaDBkfrUbDnt2hWzyqV/SeH6KbWnjG3mFk=
